version: "3.7"

services:
  sqldb:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DATABASE: go-tracker 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - 27222:5432
    volumes:
       - ./db:/var/lib/postgres

volumes:
  go-tracker: 



