version: "3.7"

services:
  sqldb:
    image: mysql:8.0.26
    restart: always
    environment:
      MYSQL_DATABASE: "gotracker" 
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_ROOT_PASSWORD: "admin"
    ports:
      - 33060:3306
    volumes:
       - ./mysqldb:/var/lib/mysql

volumes:
  gotracker: 



