version: "3.7"

services:
  gotracker:
    image: golang:1.17
    ports:
      - 3000:3000
        #command: sh -c "go get -d -v . && go install -v ."
    working_dir: /go-gotracker/src 
    volumes:
      - ./go-gotracker:/src
    environment:
      MYSQL_HOST: sqldb 
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DB: activities

  sqldb:
    image: mysql:8.0.26
    restart: always
    environment:
      MYSQL_DATABASE: "activities"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_ROOT_PASSWORD: "admin"
    ports:
      - 3001:3001
    volumes:
      - ./mysqldb:/var/lib/mysql

volumes:
  gotracker: 



