version: "3.7"

services:
  influxdb:
    image: influxdb:latest
    container_name: go-gotracker
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - ./db:/var/lib/influxdb
    environment:
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gogotracker
    ports:
      - "27222:5432"
    volumes:
      - ./db:/var/lib/postgres

volumes:
  go-tracker: 
